# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "24ee4103c165d67609fd3b4770782556"
name = "test-cf"
handle = "test-cf-1"
application_url = "https://september-twist-cover-currently.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "brandon-dev-marketplace.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = ""

[auth]
redirect_urls = [
  "https://september-twist-cover-currently.trycloudflare.com/auth/callback",
  "https://september-twist-cover-currently.trycloudflare.com/auth/shopify/callback",
  "https://september-twist-cover-currently.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-04"

[pos]
embedded = false
